### ISSUE TITLE
Resources Extract/Inject (possible bug)

### ISSUE THREAD

**Issue by ahaller** [modxcms/teleport#10]
I've extracted my site using resources.tpl.json file. When I attempt injection on a separate install, I get the following error: 
`(ERROR @ bin/teleport) Instantiated a derived class modDocument that is not a subclass of the requested class modSymLink`
It then hangs for a minute, and PHP runs out of memory:
`Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 78 bytes) in /Users/ahaller/Sites/git/fw_modx/fw_core_ks2ge/model/modx/modresource.class.php on line 882`

Do you know how I can resolve this issue?

**Comment by opengeek** [comment]
The resources.tpl.json uses the context_key + uri of each resource to determine uniqueness. This means the sites would have to be using friendly urls. Is it possible this was related to using this without the friendly_url feature enabled in MODX?
