### ISSUE TITLE
Latest teleport.phar distribution not up to date

### ISSUE THREAD

**Issue by jchirschy** [modxcms/teleport#14]
Hello,

It seems that the latest [teleport.phar](http://modx.s3.amazonaws.com/releases/teleport/teleport.phar) distribution is not up to date. 
For example, this distribution does not contain `src/Teleport/Transport/FileVehicle.php` which is a must have to use [Symfony2 finder](http://symfony.com/doc/current/components/finder.html) component as described in this [thread](http://forums.modx.com/thread/95374/teleport-extracting-elements-without-supplementing#dis-post-516354).

**Comment by opengeek** [comment]
The phar version was just compiled from the v1.0.0 release tag — let us know if you have problems still.
