### ISSUE TITLE
Missing support for modAccessNamespace?

### ISSUE THREAD

**Issue by pixelchutes** [modxcms/teleport#16]
After learning a little more about Teleport, [this commit](https://github.com/modxcms/revolution/commit/7cb54167e0997e2c6dcf8b37265c9cd1443a333d#diff-925bd05c1c34060591790509c14ef0db) came to mind...

Should Teleport's [complete.tpl.json](https://github.com/modxcms/teleport/blob/5690df7e5b228a235176ef49839747cbefc4a25f/tpl/complete.tpl.json#L35) be updated to include `modAccessNamespace`? (and perhaps `complete_db.tpl.json`?)

I don't know if I'm way off base here, so please close if necessary.

**Comment by opengeek** [comment]
Indeed—good catch Mike. Also probably need to make sure adding them does not break anything for users on older versions.

**Comment by opengeek** [comment]
Looks like it also affects the `develop.tpl.json`
