### ISSUE TITLE
Logging Actions

### ISSUE THREAD

**Issue by bwente** [modxcms/teleport#17]
On a successful extraction action add an entry to Manager Log. Or someplace to track them

$modx->logManagerAction($eventName,'modUser',$user->get('id'));

**Comment by opengeek** [comment]
I'm not sure the manager log is the appropriate place to log Teleport actions. At least, there is no MODX user involved in running teleport.

Would some more robust logging options for Teleport itself help any? Or can you share your use case?

**Comment by bwente** [comment]
That's true there isn't a user running teleport. We have worked around the issue, by creating a wrapper for teleport to create snapshots and moves them to a production environment. It logs those actions to the manger log.

![managerlog](https://cloud.githubusercontent.com/assets/371964/9181535/82e55698-3f73-11e5-8efc-5f322b85b46f.png)
