### ISSUE TITLE
Obscure error from Extract

### ISSUE THREAD

**Issue by Omeryl** [modxcms/teleport#21]
When running extract, regardless of environment, this is the result for a few sites:

```
[2015-07-15 19:30:11] (ERROR @ teleport.phar) Could not load class: modAccessNamespace from mysql.modaccessnamespace.
[2015-07-15 19:30:11] (ERROR @ teleport.phar) Could not load class: modAccessNamespace from mysql.modaccessnamespace.

Fatal error: Call to a member function prepare() on null in /Applications/MAMP/htdocs/basic.modx/core/xpdo/xpdo.class.php on line 2921
```

No other useful information as far as I can tell.

**Comment by Omeryl** [comment]
This only happens when using develop template, not the complete template. Garry suggests it has to do with the things we added for 2.4 package dependency support that got missed for adding in complete template.

**Comment by opengeek** [comment]
FWIW, `modAccessNamespace` has nothing to do with package dependencies. This is for adding ACLs to component namespaces so access can be restricted to specific ones. Also, this only explains the ERROR messages, not the Fatal Error that is stopping the process. More information on the error stopping the process is what is needed.

**Comment by opengeek** [comment]
Latest [teleport.phar](http://modx.s3.amazonaws.com/releases/teleport/teleport.phar) has been updated with this fix. Please test this out.

**Comment by Omeryl** [comment]
As far as I can tell, the issue is resolved. Thanks @opengeek!
