### ISSUE TITLE
Element Snapshots not working in 3.x

### ISSUE THREAD

**Issue by matdave** [modxcms/teleport#41]
@opengeek I think the Element template is wrong: https://github.com/modxcms/teleport/blob/2.x/tpl/elements.tpl.json 

I could be mistaken, but I believe all the referencies to "xPDO\\Transport\\" classes should be "Teleport\\Transport\\".

**Comment by opengeek** [comment]
You are indeed wrong. 😉

**Comment by matdave** [comment]
Purportedly fixed in 2.0.3. Closing for now.
