### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sepiariver** [modxcms/teleport#6]
Got this error message performing action=Profile

PHP Fatal error:  Declaration of Teleport\Request\Request::getResults() must be compatible with that of Teleport\Request\RequestInterface::getResults() in phar:///data/www2/public/teleport/teleport.phar/src/Teleport/Request/Request.php on line 24

phpinfo() in IM

**Comment by matdave** [comment]
same thing here with <pre>php teleport.phar --action=Profile --name="BaseSite" --code=basesite --core_path=/path/to/core232/ --config_key=config</pre>
